### ISSUE TITLE
create a ReplicateAPIService

### ISSUE THREAD

**Issue by enyason** [enyason/replicate-kotlin#2]
ReplicateAPIService will be an interface defining HTTP methods that interact with Replicate API.

Retrofit should be added as a dependency to create this interface properly.

**Comment by mayorjay** [comment]
I think it will be better to have individual interfaces for specific APIs, e.g. PredictionAPIService, etc. instead of having ReplicateAPIService which may end up having so many methods

**Comment by enyason** [comment]
> I think it will be better to have individual interfaces for specific APIs, e.g. PredictionAPIService, etc. instead of having ReplicateAPIService which may end up having so many methods

I agree with this. I will open a new issue for this.
