### ISSUE TITLE
Getting result but only starting result 

### ISSUE THREAD

**Issue by srdrakcay** [enyason/replicate-kotlin#38]
Helllo Im using replicate but I have one issues her is my code :

    suspend fun isUltrasound(imagePath: String): Flow<Prediction<PredictionResponse>?> = flow {
        val inputData = mapOf(
            "top_p" to 1,
            "prompt" to "my prompt ",
            "max_tokens" to 1,
            "temperature" to 0.2,
            "image" to imagePath
        )

        val predictable = PredictionData(
            input = inputData,
            versionId = "versionId"
        )

        val predictionTask = client.createPrediction<PredictionResponse>(predictable)
        val prediction = predictionTask.await()
        emit(prediction)
    }  

I m using this code for prediction after the prediction done prediction getting first response not last or every response. After prediction finish prediction result  response  status  becoming STARTİNG but prediction already SUCCESS is there any recommandation for this issue please let me know

**Comment by enyason** [comment]
> Helllo Im using replicate but I have one issues her is my code :
> 
> ```
> suspend fun isUltrasound(imagePath: String): Flow<Prediction<PredictionResponse>?> = flow {
>     val inputData = mapOf(
>         "top_p" to 1,
>         "prompt" to "my prompt ",
>         "max_tokens" to 1,
>         "temperature" to 0.2,
>         "image" to imagePath
>     )
> 
>     val predictable = PredictionData(
>         input = inputData,
>         versionId = "versionId"
>     )
> 
>     val predictionTask = client.createPrediction<PredictionResponse>(predictable)
>     val prediction = predictionTask.await()
>     emit(prediction)
> }  
> ```
> 
> I m using this code for prediction after the prediction done prediction getting first response not last or every response. After prediction finish prediction result response status becoming STARTİNG but prediction already SUCCESS is there any recommandation for this issue please let me know

Hello @srdrakcay can you confirm which model you are using?

Also if you can, share an example of the image path in your `inputData`

Also, when the prediction is successful, does the prediction output contain a valid result?

**Comment by srdrakcay** [comment]
My image path is just imageUrl and yes when the prediction result getting success I can get the output correctly but prediction giving the first stating response ı can see the correct response from the logs everything looks fine except getting the response just want to get success response but     val prediction = predictionTask.await() giving the first request response

**Comment by enyason** [comment]
Can you share the model name and version you are using so I can try to reproduce this issue on my end? @srdrakcay

**Comment by srdrakcay** [comment]
Here is the model name yorickvp/llava-13b I am not authorized to share version

**Comment by enyason** [comment]
Hey @srdrakcay , I have looked into it, It seems there is something wrong with how defined your output type. Find below 2 working approaches. 

Without flow: This returns the entire output when the prediction is done
```

val client = Replicate.client("valid_token")

val inputData = mapOf(
        "image" to "https://replicate.delivery/pbxt/KRULC43USWlEx4ZNkXltJqvYaHpEx2uJ4IyUQPRPwYb8SzPf/view.jpg",
        "prompt" to "Are you allowed to swim here?"
    )
    val predictable = object : Predictable {
        override val modelId: String = "yorickvp/llava-13b"
        override val versionId: String = "80537f9eead1a5bfa72d5ac6ea6414379be41d4d4f6679fd776e9535d1eb58bb"
        override val input: Map<String, Any> = inputData
    }

    val predictionTask = client.createPrediction<List<String>>(predictable)

    val prediction = predictionTask.await()

    println(prediction.toString())
    println(prediction?.status)
```

console log:
```

Prediction(id=y8cfgr9ae5rgp0cj38trn4mnjr, model=yorickvp/llava-13b, version=80537f9eead1a5bfa72d5ac6ea6414379be41d4d4f6679fd776e9535d1eb58bb, input={image=https://replicate.delivery/pbxt/KRULC43USWlEx4ZNkXltJqvYaHpEx2uJ4IyUQPRPwYb8SzPf/view.jpg, prompt=Are you allowed to swim here?}, logs=, output=[Yes, , you , are , allowed , to , swim , in , the , lake, , as , there , is , a , pier , extending , out , into , the , water. , The , pier , provides , a , safe , and , accessible , point , for , people , to , enter , the , lake , and , enjoy , swimming , or , other , water , activities.], error=null, status=SUCCEEDED, source=null, createdAt=2024-09-22T14:49:04.881Z, startedAt=2024-09-22T14:49:04.887290951Z, completedAt=2024-09-22T14:49:07.601302843Z, metrics=Metrics(predictTime=2.714011883, totalTime=null), urls=Urls(cancel=https://api.replicate.com/v1/predictions/y8cfgr9ae5rgp0cj38trn4mnjr/cancel, get=https://api.replicate.com/v1/predictions/y8cfgr9ae5rgp0cj38trn4mnjr, stream=https://stream-g.svc.us.c.replicate.net/v1/streams/a35h6lnlpuza7evr2223sxwst2uqcr5irwbh7v5qhrtawgry73ba))
SUCCEEDED
```

<img width="1377" alt="Screenshot 2024-09-22 at 3 50 58 PM" src="https://github.com/user-attachments/assets/568b0f6c-59eb-4847-b8bd-d0bd243bf583">


using kotlin flow: This will stream the responses in chucnks

```
  val predictionTask = client.createPrediction<Any>(predictable, stream = true)
    
    predictionTask.result?.let { prediction ->
        prediction.stream().collect { response ->
            println(response)

        }
    }

```

Output schema reference - https://replicate.com/yorickvp/llava-13b/api/schema


I hope this helps resolve your issue.

**Comment by srdrakcay** [comment]
val predictionTask = client.createPrediction<List<String>>(predictable) After using this one its found the correct soluton of it when the giving the Response class that I made it from the log output. Thats not getting the response correctliy thats ı was tell about. After change the response <List<String>> its worked thanks for the help .
